name: Build and Push Frontend Image

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get version from package.json
        id: get_version
        run: |
          cd frontend
          VERSION=$(jq -r '.version' package.json)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: If Repository Owner with upper case will drop an error need lower cases
        id: get_lowercase
        run: echo "ghcr.io/${{ github.repository_owner }}/frontend:${{ steps.get_version.outputs.version }}  | tr '[:upper:]' '[:lower:]'" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: |
            ghcr.io/`${{ github.repository_owner }}/frontend:${{ steps.get_version.outputs.version }}  | tr '[:upper:]' '[:lower:]'`/frontend:${{ steps.get_version.outputs.version }}
            ghcr.io/`${{ github.repository_owner }}/frontend:${{ steps.get_version.outputs.version }}  | tr '[:upper:]' '[:lower:]'`/frontend:latest
